from pathlib import Path

MARQUEE = r'''const imgGroup = "https://www.figma.com/api/mcp/asset/415251a7-9968-4a95-8bc8-be342bbc0253";
const imgGroup1 = "https://www.figma.com/api/mcp/asset/8ed93a55-05bd-4884-9701-4e3c04793882";
const imgGroup2 = "https://www.figma.com/api/mcp/asset/f47e0777-530d-45a2-ab62-bf4a6fdfe8e7";
const imgGroup3 = "https://www.figma.com/api/mcp/asset/1870bbd1-0e1e-4e7c-b6e2-e15d3db07933";
const imgGroup4 = "https://www.figma.com/api/mcp/asset/157ce8e9-9fe2-4223-9a5e-045beebeca22";
const imgGroup5 = "https://www.figma.com/api/mcp/asset/3bf37d72-7c8a-4a5d-af0e-893b8a255915";

export default function MarqueeSection() {
  return (
    <div className="border-[#dbdcdf] border-b border-solid border-t relative size-full" data-node-id="50:509" data-name="Section - wpr marquee area start">
'''

# Write marquee in parts - read from external file generated by fetching
# For brevity, read the template from stdin or use subprocess
